from pathlib import Path

def build_markdown_report(records):
    """
    Membuat teks laporan lengkap dalam format Markdown dari data rekap.
    Args:
        records (list): Daftar dictionary hasil dari RekapKelas.rekap().
    Returns:
        str: Teks lengkap laporan dalam format Markdown.
    """
    lines = [
        "# Rekap Kinerja Mahasiswa",
        "",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---:|---:|:---|",
    ]

    for r in records:
        pred = letter_grade(r["akhir"])
        lines.append(
            "| {nim} | {nama} | {hadir:.2f} | {akhir:.2f} | {pred} |".format(
                nim=r["nim"],
                nama=r["nama"],
                hadir=r["hadir"],
                akhir=r["akhir"],
                pred=pred,
            )
        )

    lines.append("")
    lines.append("Generated by student_performance_tracker.")
    return "\n".join(lines)


def save_text(path, content):
    """
    Menyimpan konten teks (content) ke sebuah file (path).
    Args:
        path (str): Lokasi file tujuan, mis. "out/report.md".
        content (str): Teks yang akan disimpan.
    """
    output_dir = Path(path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    try:
        Path(path).write_text(content, encoding="utf-8")
    except Exception as e:
        raise IOError(f"Gagal menyimpan file ke {path}: {e}")


def letter_grade(score):
    """
    Mengubah skor angka (0-100) menjadi predikat huruf (A-E).
    """
    if score >= 85:
        return "A"
    if score >= 75:
        return "B"
    if score >= 65:
        return "C"
    if score >= 50:
        return "D"
    return "E"


# 🆕 Tambahan fungsi untuk laporan HTML
def build_html_report(records):
    """
    Menghasilkan laporan dalam format HTML dari data rekap mahasiswa.
    """
    rows_html = ""
    for r in records:
        color = (
            "#4CAF50" if r["predikat"] == "A" else
            "#4C3DA5" if r["predikat"] == "B" else
            "#FFC107" if r["predikat"] == "C" else
            "#F44336"
        )
        rows_html += f"""
        <tr>
            <td>{r['nim']}</td>
            <td>{r['nama']}</td>
            <td>{r['hadir']:.2f}%</td>
            <td>{r['akhir']:.2f}</td>
            <td style='color:{color}'>{r['predikat']}</td>
        </tr>
        """

    html = f"""<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Rekap Mahasiswa</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #2196F3; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: center; }}
        th {{ background-color: #2196F3; color: white; }}
        tr:nth-child(even) {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    <h1>📊 Rekap Kinerja Mahasiswa</h1>
    <table>
        <tr>
            <th>NIM</th>
            <th>Nama</th>
            <th>Hadir (%)</th>
            <th>Nilai Akhir</th>
            <th>Predikat</th>
        </tr>
        {rows_html}
    </table>
</body>
</html>
"""
    return html